name: Qv2ray build matrix - cmake

on:
  push:
    branches:
      - dev
  release:
    types: [prereleased]
  workflow_dispatch:

jobs:
  check_commit_msg:
    outputs:
      commit_message: ${{ steps.get_message.outputs.message }}
    name: Check if the workflow has been disabled.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get commit message
        id: get_message
        run: |
          echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.after }} | tr '\n' ' ')"
          echo "message=\"$(git log --format=%B -n 1 ${{ github.event.after }} | tr '\n' ' ')\"" >> $GITHUB_ENV
  build:
    needs: check_commit_msg
    if: ${{ !contains( needs.check_commit_msg.outputs.commit_message, '!QT5') }}
    strategy:
      matrix:
        #platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [macos-latest, osx-arm64]
        #build_type: [RelWithDebInfo, Release]
        build_type: [Release]
        qt_version: [5.15.0]
      fail-fast: false

    runs-on: ${{ matrix.platform }}
    env:
      _QV2RAY_BUILD_INFO_: "Qv2ray built from Github Action"
      _QV2RAY_BUILD_EXTRA_INFO_: "qt${{ matrix.qt_version }}-${{ github.sha }}-ci.${{ matrix.platform }}"
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Get the version
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Checking out sources
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      # --------------------------------------------------------
      - name: macOS - ${{ matrix.platform }} - Build preparation - Install Packages
        run: |
          brew install protobuf grpc ninja pkg-config
          brew install qt@6 grpc cmake v2ray openssl@3
          git clone https://github.com/Qv2ray/macdeployqt-patched
          cd macdeployqt-patched
          mkdir build; cd build;
          cmake .. -DCMAKE_BUILD_TYPE=Release; cmake --build .
          cp -v ./macdeployqt /tmp/bin/macdeployqt
      # ========================================================================================================= Generate MakeFile and Build
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install -g appdmg
      - name: macOS - ${{ matrix.platform }} - Generate Dependencies and Build
        shell: bash
        env:
          PKG_CONFIG_PATH: /usr/local/opt/openssl@3/lib/pkgconfig
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=installed \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=13.2 \
            -DDS_STORE_SCRIPT=ON \
            -DQV2RAY_DEFAULT_VASSETS_PATH=/opt/homebrew/etc/v2ray \
            -DQV2RAY_DEFAULT_VCORE_PATH=/opt/homebrew/bin/v2ray
          cmake --build . --parallel $(sysctl -n hw.logicalcpu)
          sudo cmake --install .
          appdmg ../assets/package_dmg.json ../Qv2ray.dmg
      # --------------------------------------------------------
      - name: macOS - ${{ matrix.platform }} - Uploading Artifact
        uses: actions/upload-artifact@master
        with:
          name: Qv2ray-${{ github.sha }}.macOS.qt${{ matrix.qt_version }}-${{ matrix.build_type }}.dmg
          path: Qv2ray.dmg
      - name: macOS - ${{ matrix.platform }} - Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Qv2ray.dmg
          asset_name: Qv2ray.${{ steps.get_version.outputs.VERSION }}.macOS.dmg
          tag: ${{ github.ref }}
          overwrite: true